apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centrifugo.fullname" . }}-config
  namespace: {{ include "centrifugo.namespace" . }}
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
data:
  config.json: |-
{{ toJson .Values.centrifugo.config| indent 4 }}
